In [211]:
#import the required libraries
import numpy as np
import pandas as pd

# Step 1 : Read the Data!

In [213]:
#give path of the source-file and store that path in a variable named census
census = 'makeSenseOfCensus.csv'

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [214]:
data = np.genfromtxt(census, delimiter = ',', skip_header =1 )
print("\nData:\n\n ", data)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [215]:
#print the type of data
type(data)

numpy.ndarray

# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [216]:
new_record = [[50,9,4,1,0,0,40,0]]

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [217]:
data = np.concatenate((data, new_record), axis=0)

In [218]:
#display after appending the new record at the end of the array.
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [219]:
age=data[:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

Find the max age and store it in a variable called 'max_age'.



In [220]:
#print the max_age
max_age=np.max(age)
max_age

90.0

Find the min age and store it in a variable called 'min_age'.

In [221]:
#print the min_age
min_age=np.min(age)
min_age

17.0

Find the mean of the age and store it in a variable called 'age_mean'.

In [222]:
#print the age_mean
age_mean=np.mean(age)
age_mean

38.06293706293706

Find the standard deviation of the age and store it in a variable called 'age_std'

In [223]:
#print the age_std
age_std=np.std(age)
age_std

13.341478176165857

# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [224]:
race=data[:,2]
race_0=data[race==0]
race_1=data[race==1]
race_2=data[race==2]
race_3=data[race==3]
race_4=data[race==4]

In [225]:
race_4

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [226]:
#len_0
len_0=len(race_0)
len_0

10

In [227]:
#len_1
len_1=len(race_1)
len_1

27

In [228]:
#len_2
len_2=len(race_2)
len_2

110

In [229]:
#len_3
len_3=len(race_3)
len_3

6

In [230]:
#len_4
len_4=len(race_4)
len_4

848

Find out which is the race with the minimum no. of citizens

In [231]:
unique, count=np.unique(race, return_counts=True)
min= unique[np.argmin(count)]
min

3.0

Find out which is the race with the minimum no. of citizens

In [232]:
max= unique[np.argmax(count)]
max

4.0

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [233]:
minority_race=min
minority_race

3.0

Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [234]:
majority_race=max
majority_race

4.0

# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [235]:
#from age column, filter out age data > 60
senior_citizens=data[age>60]
senior_citizens

array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [236]:
working_hours_sum=np.sum(senior_citizens[:,6])
working_hours_sum

1917.0

c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [237]:
senior_citizens_len=len(senior_citizens)
senior_citizens_len

61

d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [238]:
avg_working_hours=working_hours_sum/senior_citizens_len

e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [239]:
print(avg_working_hours)

31.42622950819672


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [240]:
edu=data[:,1]
high=data[edu>10]
print("high\n",high)
low=data[edu<=10]
print("low\n",low)

high
 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [28. 13.  2. ...  0. 40.  0.]
 ...
 [45. 14.  4. ...  0. 45.  0.]
 [48. 13.  4. ...  0. 58.  1.]
 [39. 13.  4. ...  0. 50.  1.]]
low
 [[38.  9.  4. ...  0. 40.  0.]
 [53.  7.  2. ...  0. 40.  0.]
 [49.  5.  2. ...  0. 16.  0.]
 ...
 [56.  9.  4. ...  0. 55.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]]


Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [241]:
avg_high_pay=np.mean(high[:,7])
avg_high_pay

0.42813455657492355

In [242]:
avg_low_pay=np.mean(low[:,7])
avg_low_pay

0.13649851632047477